### ISSUE TITLE
Vertikaler YouTube Shorts?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-video#171]
Prüfen.

**Comment by lukasniebler** [comment]
Wenn Shortcode aspectratio="9/16" genutzt wird, muss iFrame bestimmte Attribute (v.a. aber width 315 und height 560 zufügen, damit die korrekte Darstellung ausgegeben wird...)

Muss in den Einstellungen des Blocks noch eingefügt werden. Ansonsten in v4

**Comment by lukasniebler** [comment]
## ToDo
- [ ] Automatisches Erkennen, welcher Provider genutzt wird
- [ ] Dynamisches Ein- und Ausblenden der AspectRatio für nicht YouTube / FAU-Videos?
- [ ] Textausrichtung für Videos, da YouTube-Shorts immer in einer fixen Pixelgröße ausgegeben werden (Linksausrichtung (default), Zentriert und Rechtsausrichtung) für einfacheres Handling im Block Editor

![Bildschirmfoto 2023-08-31 um 16 20 59](https://github.com/RRZE-Webteam/rrze-video/assets/58593037/b6e6e8ee-ee4a-4d13-9a06-c4d6fc24f15c)

## Einstellungen
Ausstehend: Automatisches Erkennen von YouTube Shorts. Automatische Vorauswahl von Landscape / Portrait-Mode
![Bildschirmfoto 2023-08-31 um 16 21 31](https://github.com/RRZE-Webteam/rrze-video/assets/58593037/b086fc80-d621-4ba9-aea3-34c0cef7e8b8)
